### ISSUE TITLE
What should I put on the following sections

### ISSUE THREAD

**Issue by ilyasahsan123** [iomarmochtar/content-plus-totp#3]
Hi Mas @iomarmochtar,

What should I put on the following sections? could you please elaborate?

<img width="505" alt="image" src="https://user-images.githubusercontent.com/14249648/231776758-379aef5b-31e0-4702-8387-0bd3412d0fd0.png">

Thanks

**Comment by iomarmochtar** [comment]
hello @ilyasahsann sorry for late to reply, `encrytion key` should be a random string to decrypting the content. `content` is something that will be encrypted is might your password since the combination results will be `[CONTENT][GENERATED_TOTP]`. `totp master` is the random key that generated in QR code page, you can inspect element in your browser to get it.
